"""Generated reports."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.enums import ReportFormat, ReportStatus, enum_type
from app.utils.time import utcnow

if TYPE_CHECKING:
    from app.models.session import AnalysisSession
    from app.models.user import User


class Report(db.Model):
    """A PDF or DOCX report for a session, generated by a background job."""

    __tablename__ = "reports"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[int] = mapped_column(
        sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"), index=True
    )
    format: Mapped[ReportFormat] = mapped_column(enum_type(ReportFormat, "format"))
    file_path: Mapped[str | None] = mapped_column(sa.String(512))
    sections: Mapped[list[str]] = mapped_column(JSONB, default=list)
    status: Mapped[ReportStatus] = mapped_column(
        enum_type(ReportStatus, "status"), default=ReportStatus.QUEUED
    )
    error_message: Mapped[str | None] = mapped_column(sa.Text)
    created_by_id: Mapped[int] = mapped_column(sa.ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), default=utcnow, server_default=sa.func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))

    session: Mapped[AnalysisSession] = relationship()
    created_by: Mapped[User] = relationship()
