"""Default catalogue of course-style topic names (the ``topic_name_catalogue`` setting).

Discovered topics are labelled with the closest of these names (by SBERT similarity) so that
lecturers see "Software Testing and Quality Assurance" rather than keyword lists. Sources: the
ACM/IEEE-CS/AAAI Computer Science Curricula 2023 (CS2023) knowledge areas and common course
titles in Nigerian computing programmes (NUC CCMAS 2023: Computer Science, Software
Engineering, Cybersecurity, Information Technology, Data Science). Administrators can edit the
list in Settings.
"""

from __future__ import annotations

TOPIC_NAMES: tuple[str, ...] = (
    # Foundations and programming
    "Introduction to Computer Science",
    "Introduction to Programming",
    "Programming in Python",
    "Programming in Java",
    "Programming in C and C++",
    "Object-Oriented Programming",
    "Functional Programming",
    "Scripting and Automation",
    "Data Structures and Algorithms",
    "Discrete Mathematics",
    "Theory of Computation",
    "Compiler Construction",
    "Formal Methods",
    "Numerical Methods",
    "Operations Research",
    "Computer Graphics",
    "Game Development",
    "Research Methods in Computing",
    # Software engineering and development
    "Software Engineering Principles",
    "Software Requirements Engineering",
    "Software Architecture and Design",
    "Software Construction",
    "Software Testing and Quality Assurance",
    "Test Automation",
    "Agile Software Development",
    "Software Project Management",
    "Software Maintenance and Evolution",
    "Version Control and Collaborative Development",
    "DevOps and Continuous Delivery",
    "Site Reliability Engineering",
    "Web Application Development",
    "Front-End Web Development",
    "Back-End Web Development",
    "Full-Stack Web Development",
    "Mobile Application Development",
    "Android Application Development",
    ".NET Application Development",
    "API Design and Integration",
    "Enterprise Systems Integration",
    "User Experience (UX) Design",
    "Human-Computer Interaction",
    "Software Product Management",
    "Technical Writing and Documentation",
    # Data and artificial intelligence
    "Database Management Systems",
    "SQL and Relational Databases",
    "NoSQL Databases",
    "Data Engineering and Data Pipelines",
    "Big Data Technologies",
    "Data Warehousing and Business Intelligence",
    "Data Analytics",
    "Data Visualisation",
    "Statistics for Data Science",
    "Data Mining",
    "Business Analytics",
    "Data Governance and Privacy",
    "Cloud Data Platforms",
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Robotics",
    # Systems, networks and cloud
    "Computer Architecture and Organisation",
    "Operating Systems",
    "Embedded Systems",
    "Internet of Things",
    "Parallel and Distributed Computing",
    "Distributed Systems",
    "Computer Networks",
    "Data Communication",
    "Wireless and Mobile Networks",
    "Network Administration",
    "Systems Administration",
    "Linux System Administration",
    "IT Infrastructure Management",
    "IT Service Management (ITIL)",
    "IT Support and Help Desk Operations",
    "Cloud Computing",
    "Cloud Infrastructure and Services",
    "Containerisation and Orchestration",
    "Virtualisation",
    "Quantum Computing Fundamentals",
    # Security
    "Cybersecurity Fundamentals",
    "Network Security",
    "Information Security Management",
    "Threat Intelligence and Vulnerability Management",
    "Security Operations and Incident Response",
    "Ethical Hacking and Penetration Testing",
    "Digital Forensics",
    "Cryptography",
    "Application Security",
    "Cloud Security",
    "Identity and Access Management",
    "Governance, Risk and Compliance",
    "Business Continuity and Disaster Recovery",
    "Security Auditing",
    "Cyber Law and Data Protection",
    # Information systems, business and society
    "Information Systems",
    "Management Information Systems",
    "Enterprise Resource Planning (ERP) Systems",
    "Business Process Management",
    "Customer Relationship Management Systems",
    "ICT Project Management",
    "E-Commerce and Digital Payments",
    "Financial Technology (FinTech)",
    "Blockchain Technology",
    "Digital Marketing",
    "Technology Entrepreneurship",
    "Innovation Management",
    "Emerging Technologies",
    "Digital Economy and Policy",
    "E-Government and Digital Public Services",
    "ICT Policy and Regulation",
    "Digital Literacy and Skills",
    "Digital Inclusion",
    "Computer Ethics and Professional Practice",
    "Communication Skills for IT Professionals",
    "Educational Technology",
    "Health Informatics",
    "Geographic Information Systems",
)
