"""Initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-24 17:18:43.675981

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # pgvector provides the VECTOR type used for passage embeddings.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "label",
            sa.Enum(
                "SKILL",
                "TOOL",
                "CERT",
                "LANGUAGE",
                name="label",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("pattern", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_patterns")),
        sa.UniqueConstraint("label", "pattern", name=op.f("uq_skill_patterns_label_pattern")),
    )
    with op.batch_alter_table("skill_patterns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_patterns_canonical_name"), ["canonical_name"], unique=False
        )

    op.create_table(
        "stop_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stop_words")),
        sa.UniqueConstraint("word", name=op.f("uq_stop_words_word")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "planner",
                "viewer",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("session_token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("session_token", name=op.f("uq_users_session_token")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action_type"), ["action_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=64), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "pdf",
                "docx",
                "txt",
                name="file_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_category",
            sa.Enum(
                "job_market",
                "institutional",
                "policy",
                "academic",
                "nuc_core",
                name="source_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "uploaded",
                "parsing",
                "ready",
                "failed",
                "archived",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("file_size > 0", name=op.f("ck_documents_file_size_positive")),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_documents_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("stored_filename", name=op.f("uq_documents_stored_filename")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_category_status", ["source_category", "processing_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_documents_uploaded_by_id"), ["uploaded_by_id"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.id"], name=op.f("fk_settings_updated_by_id_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "nuc_core_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_nuc_core_versions_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_nuc_core_versions_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nuc_core_versions")),
        sa.UniqueConstraint("document_id", name=op.f("uq_nuc_core_versions_document_id")),
    )
    with op.batch_alter_table("nuc_core_versions", schema=None) as batch_op:
        batch_op.create_index(
            "uq_nuc_core_versions_single_active",
            ["is_active"],
            unique=True,
            postgresql_where=sa.text("is_active"),
        )

    op.create_table(
        "passages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalised_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_passages_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passages")),
        sa.UniqueConstraint(
            "document_id", "position", name=op.f("uq_passages_document_id_position")
        ),
    )
    with op.batch_alter_table("passages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_passages_document_id"), ["document_id"], unique=False)

    op.create_table(
        "analysis_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("session_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_stage", sa.String(length=32), nullable=True),
        sa.Column("progress_percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "parameter_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("nuc_core_version_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100",
            name=op.f("ck_analysis_sessions_progress_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_analysis_sessions_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["nuc_core_version_id"],
            ["nuc_core_versions.id"],
            name=op.f("fk_analysis_sessions_nuc_core_version_id_nuc_core_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_sessions")),
    )
    with op.batch_alter_table("analysis_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_sessions_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_sessions_status"), ["status"], unique=False)

    op.create_table(
        "document_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("processing_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_sessions_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analysis_sessions.id"],
            name=op.f("fk_document_sessions_session_id_analysis_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sessions")),
        sa.UniqueConstraint(
            "document_id", "session_id", name=op.f("uq_document_sessions_document_id_session_id")
        ),
    )
    with op.batch_alter_table("document_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_sessions_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_sessions_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "nlp_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "result_type",
            sa.Enum(
                "tfidf",
                "entities",
                "topics",
                "similarity",
                name="result_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analysis_sessions.id"],
            name=op.f("fk_nlp_results_session_id_analysis_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nlp_results")),
        sa.UniqueConstraint(
            "session_id", "result_type", name=op.f("uq_nlp_results_session_id_result_type")
        ),
    )
    with op.batch_alter_table("nlp_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nlp_results_session_id"), ["session_id"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "topic_id",
            sa.Integer(),
            nullable=False,
            comment="BERTopic topic number within the session",
        ),
        sa.Column("auto_title", sa.String(length=255), nullable=False),
        sa.Column("topic_title", sa.String(length=255), nullable=False),
        sa.Column("topic_description", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ner_score", sa.Float(), nullable=False),
        sa.Column("topic_score", sa.Float(), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("max_similarity", sa.Float(), nullable=False),
        sa.Column("closest_nuc_passage_id", sa.Integer(), nullable=True),
        sa.Column(
            "overlap_status",
            sa.Enum(
                "Potential Duplicate",
                "No Significant Overlap",
                name="overlap_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "planner_decision",
            sa.Enum(
                "accepted",
                "rejected",
                "flagged",
                name="planner_decision",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("planner_notes", sa.Text(), nullable=True),
        sa.Column("decided_by_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "composite_score BETWEEN 0 AND 1", name=op.f("ck_recommendations_composite_score_range")
        ),
        sa.CheckConstraint(
            "ner_score BETWEEN 0 AND 1", name=op.f("ck_recommendations_ner_score_range")
        ),
        sa.CheckConstraint(
            "novelty_score BETWEEN 0 AND 1", name=op.f("ck_recommendations_novelty_score_range")
        ),
        sa.CheckConstraint(
            "topic_score BETWEEN 0 AND 1", name=op.f("ck_recommendations_topic_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["closest_nuc_passage_id"],
            ["passages.id"],
            name=op.f("fk_recommendations_closest_nuc_passage_id_passages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name=op.f("fk_recommendations_decided_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analysis_sessions.id"],
            name=op.f("fk_recommendations_session_id_analysis_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
        sa.UniqueConstraint("session_id", "rank", name=op.f("uq_recommendations_session_id_rank")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendations_planner_decision"), ["planner_decision"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "format",
            sa.Enum(
                "pdf", "docx", name="format", native_enum=False, create_constraint=True, length=32
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processing",
                "completed",
                "failed",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_reports_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["analysis_sessions.id"],
            name=op.f("fk_reports_session_id_analysis_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_session_id"), ["session_id"], unique=False)

    op.create_table(
        "curriculum_maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(length=16), nullable=False),
        sa.Column("course_title", sa.String(length=255), nullable=False),
        sa.Column("credit_units", sa.Integer(), nullable=False),
        sa.Column(
            "prerequisites",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "learning_outcomes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credit_units IN (1, 2, 3)", name=op.f("ck_curriculum_maps_credit_units_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_curriculum_maps_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_curriculum_maps_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_maps")),
        sa.UniqueConstraint("recommendation_id", name=op.f("uq_curriculum_maps_recommendation_id")),
    )
    op.create_table(
        "recommendation_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.Integer(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("fk_recommendation_evidence_passage_id_passages"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_evidence_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_evidence")),
        sa.UniqueConstraint(
            "recommendation_id",
            "passage_id",
            name=op.f("uq_recommendation_evidence_recommendation_id_passage_id"),
        ),
    )
    with op.batch_alter_table("recommendation_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_evidence_passage_id"), ["passage_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_evidence_recommendation_id"),
            ["recommendation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_evidence_recommendation_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_evidence_passage_id"))

    op.drop_table("recommendation_evidence")
    op.drop_table("curriculum_maps")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_session_id"))

    op.drop_table("reports")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_session_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_planner_decision"))

    op.drop_table("recommendations")
    with op.batch_alter_table("nlp_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nlp_results_session_id"))

    op.drop_table("nlp_results")
    with op.batch_alter_table("document_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_sessions_session_id"))
        batch_op.drop_index(batch_op.f("ix_document_sessions_document_id"))

    op.drop_table("document_sessions")
    with op.batch_alter_table("analysis_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_sessions_created_by_id"))

    op.drop_table("analysis_sessions")
    with op.batch_alter_table("passages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passages_document_id"))

    op.drop_table("passages")
    with op.batch_alter_table("nuc_core_versions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_nuc_core_versions_single_active", postgresql_where=sa.text("is_active")
        )

    op.drop_table("nuc_core_versions")
    op.drop_table("settings")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_uploaded_by_id"))
        batch_op.drop_index("ix_documents_category_status")

    op.drop_table("documents")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action_type"))

    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("stop_words")
    with op.batch_alter_table("skill_patterns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_patterns_canonical_name"))

    op.drop_table("skill_patterns")
    # ### end Alembic commands ###
    # The vector extension is left installed; other databases on the server may use it.
