"""Add document content hash

Revision ID: 0002_document_content_hash
Revises: 0001_initial_schema
Create Date: 2026-09-24 22:52:23.018414

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = "0002_document_content_hash"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content_hash", sa.String(length=64), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_documents_content_hash"), ["content_hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_content_hash"))
        batch_op.drop_column("content_hash")

    # ### end Alembic commands ###
