"""Add session stage timings

Revision ID: 0003_session_stage_timings
Revises: 0002_document_content_hash
Create Date: 2026-09-25 04:59:21.588228

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0003_session_stage_timings"
down_revision = "0002_document_content_hash"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stage_timings",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'{}'::jsonb"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_sessions", schema=None) as batch_op:
        batch_op.drop_column("stage_timings")

    # ### end Alembic commands ###
