"""initial schema

Revision ID: 30fcec4b01cf
Revises: 
Create Date: 2026-09-23 21:49:26.773579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fcec4b01cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Curriculum Planner', 'Viewer', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('analysis_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Processing', 'Completed', 'Failed', name='session_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('parameter_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_stage', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_analysis_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_analysis_sessions'))
    )
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action_timestamp'), ['action_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'txt', name='file_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_category', sa.Enum('NUC Core Reference', 'Job Market Data', 'Institutional Document', 'Policy Document', 'Academic Literature', name='source_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('processing_status', sa.Enum('Uploaded', 'Parsed', 'Failed', name='document_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_source_category'), ['source_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('document_sessions',
    sa.Column('doc_session_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('processing_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_document_sessions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.session_id'], name=op.f('fk_document_sessions_session_id_analysis_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_session_id', name=op.f('pk_document_sessions')),
    sa.UniqueConstraint('document_id', 'session_id', name='uq_document_session')
    )
    with op.batch_alter_table('document_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sessions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sessions_session_id'), ['session_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(length=255), nullable=False),
    sa.Column('topic_description', sa.Text(), nullable=True),
    sa.Column('ner_score', sa.Float(), nullable=False),
    sa.Column('topic_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=True),
    sa.Column('overlap_status', sa.Enum('Potential Duplicate', 'No Significant Overlap', name='overlap_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('planner_decision', sa.Enum('Accepted', 'Rejected', 'Flagged', name='planner_decision', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('planner_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('composite_score >= 0 AND composite_score <= 1', name=op.f('ck_recommendations_composite_score_range')),
    sa.CheckConstraint('max_similarity >= 0 AND max_similarity <= 1', name=op.f('ck_recommendations_max_similarity_range')),
    sa.CheckConstraint('ner_score >= 0 AND ner_score <= 1', name=op.f('ck_recommendations_ner_score_range')),
    sa.CheckConstraint('novelty_score >= 0 AND novelty_score <= 1', name=op.f('ck_recommendations_novelty_score_range')),
    sa.CheckConstraint('topic_score >= 0 AND topic_score <= 1', name=op.f('ck_recommendations_topic_score_range')),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.session_id'], name=op.f('fk_recommendations_session_id_analysis_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_composite_score'), ['composite_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_session_id'), ['session_id'], unique=False)

    op.create_table('curriculum_maps',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.CheckConstraint('credit_units IN (1, 2, 3)', name=op.f('ck_curriculum_maps_credit_units_allowed')),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.rec_id'], name=op.f('fk_curriculum_maps_rec_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', name=op.f('pk_curriculum_maps'))
    )
    with op.batch_alter_table('curriculum_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_maps_rec_id'), ['rec_id'], unique=False)

    op.create_table('nlp_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('doc_session_id', sa.Integer(), nullable=False),
    sa.Column('tfidf_keywords', sa.JSON(), nullable=True),
    sa.Column('ner_entities', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['doc_session_id'], ['document_sessions.doc_session_id'], name=op.f('fk_nlp_results_doc_session_id_document_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_nlp_results'))
    )
    with op.batch_alter_table('nlp_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nlp_results_doc_session_id'), ['doc_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nlp_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nlp_results_doc_session_id'))

    op.drop_table('nlp_results')
    with op.batch_alter_table('curriculum_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_maps_rec_id'))

    op.drop_table('curriculum_maps')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_session_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_composite_score'))

    op.drop_table('recommendations')
    with op.batch_alter_table('document_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_document_sessions_document_id'))

    op.drop_table('document_sessions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_source_category'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_user_id'))

    op.drop_table('analysis_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
